import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'core/theme/app_theme.dart';
import 'core/navigation/app_router.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();

  // Set preferred orientations
  SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  runApp(
    const ProviderScope(
      child: DeuKartenApp(),
    ),
  );
}

class DeuKartenApp extends ConsumerWidget {
  const DeuKartenApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // Note: appRouterProvider is generated by riverpod_generator
    final router = ref.watch(appRouterProvider);

    return MaterialApp.router(
      title: 'DeuKarten',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme,
      routerConfig: router,
    );
  }
}
